### ISSUE TITLE
Make gh-pages the main branch

### ISSUE THREAD

**Issue by bittner** [kaspesla/ev3_scratch#5]
It's a bit confusing that the repository seems to be empty [when you land here](https://github.com/kaspesla/ev3_scratch).

Can you make the `gh-pages` branch the main branch on your [repository branches page](https://github.com/kaspesla/ev3_scratch/branches)? This way all files would be listed by default  when you land at this repository.

**Comment by kaspesla** [comment]
will do; thanks for the tip!
-Ken
